import "./globals.css";
import Nav from "./components/nav";
import { ViewTransitions } from "next-view-transitions";

export const metadata = {
  title: "teste Studio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body className=" antialiase">
          <Nav />

          {children}
        </body>
      </html>
    </ViewTransitions>
  );
}
