import "./globals.css";
import Nav from "./components/nav";

export const metadata = {
  title: "teste Studio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" antialiase">
        <Nav />

        {children}
      </body>
    </html>
  );
}
